# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a1aaabeb2af54018198ecee66137741a3992680826dce9bf164c65375b473be4f213dbbecb2a5605771b20cc876632107efcf296aa1f3dfdfac3de0f4c44e79

test:
  secret_key_base: 5f7f2e9607270505fa93d21dac4523f2fb4418dfcc05ecd8c7dda1825fae19afed24dc0f252f091034f3a4bce7ce0676df9edf8732b4f0b62c8ff3db1e2f8b1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
